USE remind_db;
GO

CREATE TABLE Tasks (
    TaskID INT IDENTITY (1,1) PRIMARY KEY,
    Title NVARCHAR(100) NOT NULL,
    Description NVARCHAR(100) NOT NULL,
    DueDate DATETIME DEFAULT GETDATE(),
    ImageUrl NVARCHAR(255) NULL,
    IsDone BIT DEFAULT 0,
)